### ISSUE TITLE
type annotations required: cannot resolve `_: serde::de::DeserializeOwned`

### ISSUE THREAD

**Issue by alardev** [paulkernfeld/ndarray-csv#6]
using rust version 1.35.0-nightly
upon attempting to follow the example from readme:

```rust
let file = File::open(file_path)?;
let mut reader = ReaderBuilder::new().from_reader(file);
let array_read = reader.deserialize_array2((2, 3))?;
```

rust reports the following compilation error:
```rust
error[E0283]: type annotations required: cannot resolve `_: serde::de::DeserializeOwned`
   --> src\main.rs:152:29
    |
152 |     let array_read = reader.deserialize_array2((5, 40))?;
    |                             ^^^^^^^^^^^^^^^^^^
```

could you provide any insights as to how to fix that?

**Comment by paulkernfeld** [comment]
In the example from the readme, the compiler is able to successfully infer the type of `array_read` because it knows that it is the same type as `array`.

You should be able to fix the snippet above by annotating the type of `array_read`, like:

```rust
let array_read: ndarray::Array2<usize> = reader.deserialize_array2((5, 40))?;
```

Please let me know if you run into any other speed bumps with `ndarray-csv`!

**Comment by alardev** [comment]
That fixed it, thanks for the help.
